const fs = require('fs');

const files = [
    'contracts/AbstractAccount.Oracle.cs',
    'contracts/AbstractAccount.StorageAndContext.cs',
    'contracts/AbstractAccount.Admin.cs',
    'contracts/AbstractAccount.ExecutionAndPermissions.cs',
    'contracts/AbstractAccount.MetaTx.cs',
    'contracts/AbstractAccount.AccountLifecycle.cs'
];

for (const file of files) {
    let content = fs.readFileSync(file, 'utf8');
    
    // AbstractAccount.Oracle.cs
    content = content.replace(/public static void SetDomeOracleByAddress\(UInt160 accountAddress, string url\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetDomeOracle\(accountId, url\);\s*\}/g, 'public static void SetDomeOracleByAddress(UInt160 accountAddress, string url) => SetDomeOracle(ResolveAccountIdByAddress(accountAddress), url);');
    content = content.replace(/public static void RequestDomeActivationByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*RequestDomeActivation\(accountId\);\s*\}/g, 'public static void RequestDomeActivationByAddress(UInt160 accountAddress) => RequestDomeActivation(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static int GetLastDomeOracleResponseCodeByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleResponseCode\(accountId\);\s*\}/g, 'public static int GetLastDomeOracleResponseCodeByAddress(UInt160 accountAddress) => GetLastDomeOracleResponseCode(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static ByteString GetLastDomeOracleResponseByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleResponse\(accountId\);\s*\}/g, 'public static ByteString GetLastDomeOracleResponseByAddress(UInt160 accountAddress) => GetLastDomeOracleResponse(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static string GetLastDomeOracleResponseUrlByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleResponseUrl\(accountId\);\s*\}/g, 'public static string GetLastDomeOracleResponseUrlByAddress(UInt160 accountAddress) => GetLastDomeOracleResponseUrl(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static bool GetLastDomeOracleUrlMatchedByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleUrlMatched\(accountId\);\s*\}/g, 'public static bool GetLastDomeOracleUrlMatchedByAddress(UInt160 accountAddress) => GetLastDomeOracleUrlMatched(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static bool GetLastDomeOracleTruthAcceptedByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleTruthAccepted\(accountId\);\s*\}/g, 'public static bool GetLastDomeOracleTruthAcceptedByAddress(UInt160 accountAddress) => GetLastDomeOracleTruthAccepted(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static bool GetLastDomeOracleUnlockAppliedByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleUnlockApplied\(accountId\);\s*\}/g, 'public static bool GetLastDomeOracleUnlockAppliedByAddress(UInt160 accountAddress) => GetLastDomeOracleUnlockApplied(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static string GetLastDomeOracleExpectedUrlByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleExpectedUrl\(accountId\);\s*\}/g, 'public static string GetLastDomeOracleExpectedUrlByAddress(UInt160 accountAddress) => GetLastDomeOracleExpectedUrl(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static string GetLastDomeOracleConfiguredUrlByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastDomeOracleConfiguredUrl\(accountId\);\s*\}/g, 'public static string GetLastDomeOracleConfiguredUrlByAddress(UInt160 accountAddress) => GetLastDomeOracleConfiguredUrl(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static bool IsDomeOracleUnlockedByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return IsDomeOracleUnlocked\(accountId\);\s*\}/g, 'public static bool IsDomeOracleUnlockedByAddress(UInt160 accountAddress) => IsDomeOracleUnlocked(ResolveAccountIdByAddress(accountAddress));');

    // AbstractAccount.StorageAndContext.cs
    content = content.replace(/public static BigInteger GetLastActiveTimestampByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetLastActiveTimestamp\(accountId\);\s*\}/g, 'public static BigInteger GetLastActiveTimestampByAddress(UInt160 accountAddress) => GetLastActiveTimestamp(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static UInt160 GetVerifierContractByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetVerifierContract\(accountId\);\s*\}/g, 'public static UInt160 GetVerifierContractByAddress(UInt160 accountAddress) => GetVerifierContract(ResolveAccountIdByAddress(accountAddress));');

    // AbstractAccount.Admin.cs
    content = content.replace(/public static void SetAdminsByAddress\(UInt160 accountAddress, Neo\.SmartContract\.Framework\.List<UInt160> admins, int threshold\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetAdmins\(accountId, admins, threshold\);\s*\}/g, 'public static void SetAdminsByAddress(UInt160 accountAddress, Neo.SmartContract.Framework.List<UInt160> admins, int threshold) => SetAdmins(ResolveAccountIdByAddress(accountAddress), admins, threshold);');
    content = content.replace(/public static Neo\.SmartContract\.Framework\.List<UInt160> GetAdminsByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetAdmins\(accountId\);\s*\}/g, 'public static Neo.SmartContract.Framework.List<UInt160> GetAdminsByAddress(UInt160 accountAddress) => GetAdmins(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static int GetAdminThresholdByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetAdminThreshold\(accountId\);\s*\}/g, 'public static int GetAdminThresholdByAddress(UInt160 accountAddress) => GetAdminThreshold(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static void SetManagersByAddress\(UInt160 accountAddress, Neo\.SmartContract\.Framework\.List<UInt160> managers, int threshold\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetManagers\(accountId, managers, threshold\);\s*\}/g, 'public static void SetManagersByAddress(UInt160 accountAddress, Neo.SmartContract.Framework.List<UInt160> managers, int threshold) => SetManagers(ResolveAccountIdByAddress(accountAddress), managers, threshold);');
    content = content.replace(/public static Neo\.SmartContract\.Framework\.List<UInt160> GetManagersByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetManagers\(accountId\);\s*\}/g, 'public static Neo.SmartContract.Framework.List<UInt160> GetManagersByAddress(UInt160 accountAddress) => GetManagers(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static int GetManagerThresholdByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetManagerThreshold\(accountId\);\s*\}/g, 'public static int GetManagerThresholdByAddress(UInt160 accountAddress) => GetManagerThreshold(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static void SetDomeAccountsByAddress\(UInt160 accountAddress, Neo\.SmartContract\.Framework\.List<UInt160> domes, int threshold, BigInteger timeoutPeriod\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetDomeAccounts\(accountId, domes, threshold, timeoutPeriod\);\s*\}/g, 'public static void SetDomeAccountsByAddress(UInt160 accountAddress, Neo.SmartContract.Framework.List<UInt160> domes, int threshold, BigInteger timeoutPeriod) => SetDomeAccounts(ResolveAccountIdByAddress(accountAddress), domes, threshold, timeoutPeriod);');
    content = content.replace(/public static Neo\.SmartContract\.Framework\.List<UInt160> GetDomeAccountsByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetDomeAccounts\(accountId\);\s*\}/g, 'public static Neo.SmartContract.Framework.List<UInt160> GetDomeAccountsByAddress(UInt160 accountAddress) => GetDomeAccounts(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static int GetDomeThresholdByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetDomeThreshold\(accountId\);\s*\}/g, 'public static int GetDomeThresholdByAddress(UInt160 accountAddress) => GetDomeThreshold(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static BigInteger GetDomeTimeoutByAddress\(UInt160 accountAddress\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetDomeTimeout\(accountId\);\s*\}/g, 'public static BigInteger GetDomeTimeoutByAddress(UInt160 accountAddress) => GetDomeTimeout(ResolveAccountIdByAddress(accountAddress));');
    content = content.replace(/public static void SetBlacklistByAddress\(UInt160 accountAddress, UInt160 target, bool isBlacklisted\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetBlacklist\(accountId, target, isBlacklisted\);\s*\}/g, 'public static void SetBlacklistByAddress(UInt160 accountAddress, UInt160 target, bool isBlacklisted) => SetBlacklist(ResolveAccountIdByAddress(accountAddress), target, isBlacklisted);');
    content = content.replace(/public static void SetWhitelistModeByAddress\(UInt160 accountAddress, bool enabled\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetWhitelistMode\(accountId, enabled\);\s*\}/g, 'public static void SetWhitelistModeByAddress(UInt160 accountAddress, bool enabled) => SetWhitelistMode(ResolveAccountIdByAddress(accountAddress), enabled);');
    content = content.replace(/public static void SetWhitelistByAddress\(UInt160 accountAddress, UInt160 target, bool isWhitelisted\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetWhitelist\(accountId, target, isWhitelisted\);\s*\}/g, 'public static void SetWhitelistByAddress(UInt160 accountAddress, UInt160 target, bool isWhitelisted) => SetWhitelist(ResolveAccountIdByAddress(accountAddress), target, isWhitelisted);');
    content = content.replace(/public static void SetMaxTransferByAddress\(UInt160 accountAddress, UInt160 token, BigInteger maxAmount\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetMaxTransfer\(accountId, token, maxAmount\);\s*\}/g, 'public static void SetMaxTransferByAddress(UInt160 accountAddress, UInt160 token, BigInteger maxAmount) => SetMaxTransfer(ResolveAccountIdByAddress(accountAddress), token, maxAmount);');
    content = content.replace(/public static void SetVerifierContractByAddress\(UInt160 accountAddress, UInt160 verifierContract\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*SetVerifierContract\(accountId, verifierContract\);\s*\}/g, 'public static void SetVerifierContractByAddress(UInt160 accountAddress, UInt160 verifierContract) => SetVerifierContract(ResolveAccountIdByAddress(accountAddress), verifierContract);');
    
    // AbstractAccount.ExecutionAndPermissions.cs
    content = content.replace(/public static object ExecuteUnifiedByAddress\(\s*UInt160 accountAddress,\s*UInt160 targetContract,\s*string method,\s*object\[\] args,\s*Neo\.SmartContract\.Framework\.List<ByteString>\? uncompressedPubKeys,\s*ByteString argsHash,\s*BigInteger nonce,\s*BigInteger deadline,\s*Neo\.SmartContract\.Framework\.List<ByteString>\? signatures\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return ExecuteUnified\(accountId, targetContract, method, args, uncompressedPubKeys, argsHash, nonce, deadline, signatures\);\s*\}/g, 'public static object ExecuteUnifiedByAddress(\n            UInt160 accountAddress,\n            UInt160 targetContract,\n            string method,\n            object[] args,\n            Neo.SmartContract.Framework.List<ByteString>? uncompressedPubKeys,\n            ByteString argsHash,\n            BigInteger nonce,\n            BigInteger deadline,\n            Neo.SmartContract.Framework.List<ByteString>? signatures) =>\n            ExecuteUnified(ResolveAccountIdByAddress(accountAddress), targetContract, method, args, uncompressedPubKeys, argsHash, nonce, deadline, signatures);');

    // AbstractAccount.MetaTx.cs
    content = content.replace(/public static BigInteger GetNonceForAddress\(UInt160 accountAddress, UInt160 signer\)\s*\{\s*ByteString accountId = ResolveAccountIdByAddress\(accountAddress\);\s*return GetNonceForAccount\(accountId, signer\);\s*\}/g, 'public static BigInteger GetNonceForAddress(UInt160 accountAddress, UInt160 signer) => GetNonceForAccount(ResolveAccountIdByAddress(accountAddress), signer);');

    fs.writeFileSync(file, content);
}
